### ISSUE TITLE
Something iffy going on with the "force_torque_sensor_controller"

### ISSUE THREAD

**Issue by imitsioni** [kth-ros-pkg/yumi#31]
There seems to be something going on when launching the aforementioned controller as sometimes, the robot starts moving as soon as you load it (which in turn makes any other controller that initializes the desired pose at the current one go bananas).
Noticed the same thing when tweaking the hiqp launch files and the one I'm using now.
As soon as the argument is removed from the controllers list, the problem disappears. 
Never encountered that behaviour when using [this](https://github.com/imitsioni/yumi/blob/optodaq_sensors/yumi_launch/launch/yumi_vel_control.launch#L24) launch file.

**Comment by diogoalmeida** [comment]
- Branch: optodaq_sensors

You _never_ encountered that behaviour on the linked launch file? Or only after you comment that line?

[Force torque sensor controller source](https://github.com/ros-controls/ros_controllers/tree/melodic-devel/force_torque_sensor_controller): The only thing the "controller" seems to be doing is taking the hardware interface for the FT sensor and publishing the measured values to a topic with the sensor name.

**Comment by imitsioni** [comment]
Update:

I am now 99% sure that the problem is the incorrect F/T sensor calibration (or the lack thereof). 
I will leave this issue open in case I am wrong.
