### ISSUE TITLE
ikfast for yumi

### ISSUE THREAD

**Issue by RYANZYC** [kth-ros-pkg/yumi#37]
Hello maintainer!I want to use ikfast instead of KDL algorithm to solve the kinematics of the manipulator.But when I follow the tutorial, the following prompt appears:

![10a5518c897716f5efd5f5fb6e19a5b](https://user-images.githubusercontent.com/34129622/56467929-eb0de700-6457-11e9-9e37-a49896972b86.jpg)
![997b8ee0f0fa5c3cb37709e3556fb66](https://user-images.githubusercontent.com/34129622/56467931-ee08d780-6457-11e9-861e-11e81b7b1684.jpg)
![f2f2c88f8a68e7c9d5065b6e8cda24e](https://user-images.githubusercontent.com/34129622/56467932-f06b3180-6457-11e9-9e67-bccd3b0cc0c3.jpg)

Have you configured the ikfast kinematics algorithm for yumi?

**Comment by diogoalmeida** [comment]
Hi,

I am not aware of anyone having configured ikfast for yumi at our lab. You might want to ask for help at the [openrave](https://github.com/rdiankov/openrave) repository page.

Best,
Diogo

PS: in future issues, consider using `` ``` `` blocks to copy and paste terminal output, like this:
```
# This is a test
$ cd /home/user/Documents
``` 

More information on that [here](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

**Comment by muh-ahmed** [comment]
Hi @RYANZYC,
Can you please guide if you are succeeded to use IKFast instead of KDL algorithm to solve the kinematics of the Yumi?

Thanks.
