### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by MERYEMTAGH** [kth-ros-pkg/yumi#39]
greetings, i have a question please.
I'm a beginner in ros and my question may be obvious. Can we use this package with Ros melodic on Ubuntu 18.04.2 LTS?

**Comment by diogoalmeida** [comment]
Hi,

You can check out the branch `melodic` when using the package! On the package directory type
```
$ git checkout melodic
```
and then compile your catkin workspace. You should be good to go.
