### ISSUE TITLE
Using Yumi with ROS + MoveIt!

### ISSUE THREAD

**Issue by beevabeeva** [kth-ros-pkg/yumi#47]
We have managed to get as far as having MoveIt (+ rviz) get the correct current position of the robot. However, when trying to execute a path to a goal position, the robot does not move.

In addition, there are no gripper topics listed. MoveIT complains about not having the gripper states:
![image](https://user-images.githubusercontent.com/19332617/69882341-8ca3c380-12d8-11ea-9fc0-db35948ddf75.png)

We followed the instructions here and on https://github.com/ethz-asl/yumi/ (after digging around in other branches to find the required backups (addition-demo, two-grippers realtime) ). We found someone with a similar issue
(https://github.com/OrebroUniversity/yumi/issues/21) but there were no detailed steps listed to solve the issue.

Any help would be appreciated.

**Comment by diogoalmeida** [comment]
Hi,

Which robot driver are you using?

**Comment by beevabeeva** [comment]
Hi @diogoalmeida,

we have tried both the ABB driver and the RWS driver.
We do not have an EGM license so we can't try that. If needed, we can try get it.

**Comment by diogoalmeida** [comment]
Completely missed this reply, apologies for that.

For future reference, we do not provide support for setting up your Yumi systems, but all our information on the topic can be found on the [wiki](https://github.com/kth-ros-pkg/yumi/wiki).

**Comment by bhomaidan1990** [comment]
I'm using **ABB driver** setup and I have the same issue with the grippers:
- The state of the grippers (open/close) is not passed from the gripper node to MoveIt, so the complete state of the robot (the grippers in particular) are not known.
-  In my case, I'm able to move the robot using **MoveIt + RViz**, and I'm able to control the grippers **using the gripper node** separately from the command line,
-  but it will be nice if we can **pass the state of the grippers to MoveIt** to control the whole robot and omit this warning, **any ideas about solving this issue**, please?

PS: I have tweaked the setup to work on my Ubuntu 20.04 (ROS Noetic) [here](https://github.com/bhomaidan1990/yumi_ros), and I have created a lunch file to launch the setup: `roslaunch yumi_moveit_config myLaunch.launch`
