### ISSUE TITLE
Unable to connect to the robot

### ISSUE THREAD

**Issue by Luc90** [kth-ros-pkg/yumi#51]
I am using Ubuntu 16.04 with ROS Melodic and I am trying to connect to the Yumi robot.
I installed the ABB driver in the Yumi controller and Gripper calibration is done normally. On the Flexpendant I have these messages "Waiting for connection" for all Task. But when I launch "roslaunch yumi_support robot_interface.launch" I have the Following error:
![Error](https://user-images.githubusercontent.com/61054917/74539238-f62d8880-4f3d-11ea-8c5b-b808bb64c54e.JPG)

Can you help me with some sugestions ?
Thank you !

**Comment by diogoalmeida** [comment]
Hi,

Sorry for the late reply. Besides what's publicly available on this repo's wiki, we do not provide support to set up your Yumi system.
