### ISSUE TITLE
rapid scripts for EGM control interface not available in yumi_hw/rapid

### ISSUE THREAD

**Issue by alibinjunaid** [kth-ros-pkg/yumi#52]
I am looking for these files in the repository to use EGM interface as per the wiki instructions to set up firmware for EGM control. However, no branches contain these files. Could anyone guide me in this regard? Thanks

EGM/TRobEGM.mod
EGM/TRobMain.mod
EGM/TRobSynchronization.sys
EGM/TRobSG.sys

**Comment by diogoalmeida** [comment]
You can check [this issue](https://github.com/kth-ros-pkg/yumi/issues/27).
