### ISSUE TITLE
Problems with the reading of the joints

### ISSUE THREAD

**Issue by kappa95** [kth-ros-pkg/yumi#62]
Hi community,
I have a big issue in my project because the readings of the joints are wrong for the left arm.
![foto1](https://user-images.githubusercontent.com/42738531/94991709-179ebb80-0585-11eb-944b-c383bc95bb70.png)
![Schermata del 2020-10-03 14-28-45](https://user-images.githubusercontent.com/42738531/94991711-19687f00-0585-11eb-8c57-da152040b4dd.png)

On the shell are shown the results of the 2 commands: rostopic echo /left_arm/joint_states/position and rostopic echo /right_arm/joint_states/position 

I compared to the results of the jogging:
![photo_2020-10-03_14-42-14](https://user-images.githubusercontent.com/42738531/94991932-b24bca00-0586-11eb-8575-9784846df7b9.jpg)
![photo_2020-10-03_14-42-18](https://user-images.githubusercontent.com/42738531/94991933-b4ae2400-0586-11eb-9ff5-0d3f8a87b3e2.jpg)

Can you help me please???

**Comment by diogoalmeida** [comment]
Hi!

If you want help with software issues, it is helpful if you indicate which commands you have run and what's the terminal output. I would also recommend that you paste the output here, within a block code (using ``` to delimit the code should work).

For example, the rostopic commands you mentions would be pasted like

```
rostopic echo /left_arm/joint_states/position 
rostopic echo /right_arm/joint_states/position
```

Without knowing which commands you issued to see those results, it is not possible to help you. 

Best,
Diogo

**Comment by kappa95** [comment]
Thank you so much Diogo!

In any case i solved the issues with the simulator and the reading of the joints using the solution of the pull requests on this repository: [https://github.com/kth-ros-pkg/yumi/pull/35](url)
