### ISSUE TITLE
Subscribe x, y, and z coordinates coming as messages from another package

### ISSUE THREAD

**Issue by hsaleem1** [kth-ros-pkg/yumi#67]
Hi there,
I am using MoveIt! Python interface (file named main.py) to do motion planning of the YuMi robot. 

I want to ask that how can I subscribe the messages (x, y and z coordinates) publishing from the another package into main.py file.

Thanks.

**Comment by imitsioni** [comment]
It depends on what exactly you want to do but more often than not, you just need to create a subscriber and its callback. :) 

[ROS Answers](https://answers.ros.org/questions/) and [ROS Tutorials](https://wiki.ros.org/ROS/Tutorials/WritingPublisherSubscriber%28python%29) have a lot of information regarding MoveIt and topic communication.
