### ISSUE TITLE
Jerky movement with RWS and MoveIt

### ISSUE THREAD

**Issue by ghost** [kth-ros-pkg/yumi#72]
Hi there,

Thanks for developing this wonderful package!

I have been using the abb_driver for some time and it works well. To use YuMi for visual servoing, recently I switched from the abb_driver to the RWS interface. The action on real YuMi with RWS and MoveIt seems quite jerky than with abb_driver. Meanwhile, I get the warning from MoveIt saying `Controller yumi/joint_traj_pos_controller_r failed with error GOAL_TOLERANCE_VIOLATED`. I suppose this is because the joints did not get to the target positions eventually.

Could I ask if this is a normal observation? I have tried to use smaller verlocity and acceleration limits, compute_cartesian_path with more waypoints, and change the longest_valid_segment_fraction of OMPL. However, they did not seem to improve the smoothness. Any idea is appreciated! Many thanks.

**Comment by ghost** [comment]
We managed to smooth out the motions by reducing the speed. This can be done by using either the flexpendant or in the RAPID scripts `ROS_motion_left.mod` and `ROS_motion_right.mod`.

**Comment by CSmallWhite** [comment]
@ghost
I'm glad to hear that you can solve this problem. I want to ask you a question: how do you change the speed in mod, and where is the speed code in mod? If you can help me, I will be very grateful. It will be of great help to my research work
